### ISSUE TITLE
Ownership of bower package

### ISSUE THREAD

**Issue by gvas** [jrcamp/knockout-jqueryui-bower#1]
I'm the developer of the knockout-jqueryui library. I've just added support for bower, and I'd like to modify the knockout-jqueryui bower package's registration to point to my original github project. Could you unregister your project as described in [bower's docs](http://bower.io/docs/creating-packages/#unregister)?

**Comment by jrcamp** [comment]
Bower is returning "GitHub.com error" when trying to unregister. Will try later.

**Comment by jrcamp** [comment]
Had the bower guys manually reassign it.

**Comment by gvas** [comment]
Thank you Jay.
